spring:
  application:
    name: wlcp-discovery
server:
   port: 8761
eureka:
   client:
      registerWithEureka: false
      fetchRegistry: false
   server:
     enable-self-preservation: false
     expected-client-renewal-interval-seconds:  1
     eviction-interval-timer-in-ms:  2000